CREATE TABLE AUTHORITY
(AUTHORITY_ID NUMBER(4) not null,
NAME VARCHAR2(100) null,
TITLE VARCHAR2(100) null,
PLACE_OF_RESIDENCE VARCHAR2(100) null,
PLACENAME_ID NUMBER(4) null,
PRIMARY KEY (AUTHORITY_ID),
FOREIGN KEY (PLACENAME_ID) REFERENCES PLACENAMES(PLACENAME_ID)); 

