CREATE TABLE ORIGIN
(ORIGIN_ID NUMBER(4) not null,
ORIGIN VARCHAR2(60) null,
PLACENAME_ID NUMBER(4) null,
PRIMARY KEY (ORIGIN_ID),
FOREIGN KEY (PLACENAME_ID) REFERENCES PLACENAMES(PLACENAME_ID)); 

