CREATE TABLE OWNER
(OWNER_ID NUMBER(4) not null,
NAME VARCHAR2(100) null,
TITLE VARCHAR2(60) null,
HOUSE VARCHAR2(60) null,
YEAR  NUMBER(4) null,
PLACENAME_ID NUMBER(4) null,
PRIMARY KEY (OWNER_ID),
FOREIGN KEY (PLACENAME_ID) REFERENCES PLACENAMES(PLACENAME_ID)); 

