CREATE TABLE PEOPLE_IMAGES
(PEOPLE_IMAGE_ID NUMBER(4) not null,
IMAGE_PATH VARCHAR2(2000) null,
PEOPLE_ID NUMBER(4) null,
PRIMARY KEY (PEOPLE_IMAGE_ID),
FOREIGN KEY (PEOPLE_ID) REFERENCES PEOPLE(PEOPLE_ID)); 
